#!/usr/bin/env bash
# Configure SSH client to connect to server without typing in a password.

Host server1
    HostName 54.164.170.176
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no